routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController as AdminAboutController;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CartController as AdminCartController;
use App\Http\Controllers\Admin\CityController as AdminCityController;
use App\Http\Controllers\Admin\CompanyDataController as AdminCompanyDataController;
use App\Http\Controllers\Admin\ContactController as AdminContactController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\PermissionController as AdminPermissionController;
use App\Http\Controllers\Admin\PrivacyPolicyController as AdminPrivacyPolicyController;
use App\Http\Controllers\Admin\ProductCategoryController as AdminProductCategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ProductImageController as AdminProductImageController;
use App\Http\Controllers\Admin\ProductRatingController as AdminProductRatingController;
use App\Http\Controllers\Admin\ProductTypeController as AdminProductTypeController;
use App\Http\Controllers\Admin\ProvinceController as AdminProvinceController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\ServiceController as AdminServiceController;
use App\Http\Controllers\Admin\SliderController as AdminSliderController;
use App\Http\Controllers\Admin\SocialController as AdminSocialController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Frontend\FrontendController as FrontendController;
use App\Http\Controllers\Frontend\OrderController as OrderController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes(['register' => true]);

Route::group(["middleware" => ["auth", 'checkPermission']], function () {
    Route::group(["prefix" => "admin/", "as" => "admin."], function () {
        Route::get("dashboard", [AdminDashboardController::class, "dashboard"])->name("dashboard");

        Route::group(["prefix" => "permission/", "as" => "permission."], function () {
            Route::get("", [AdminPermissionController::class, "index"])->name("index");
            Route::get('create', [AdminPermissionController::class, "create"])->name('create');
            Route::post("store", [AdminPermissionController::class, "store"])->name("store");
        });
        Route::group(["prefix" => "role/", "as" => "role."], function () {
            Route::get("", [AdminRoleController::class, 'index'])->name("index");
            Route::get("create", [AdminRoleController::class, 'create'])->name("create");
            Route::post("store", [AdminRoleController::class, 'store'])->name('store');
            Route::get("edit/{id}", [AdminRoleController::class, 'edit'])->name('edit');
            Route::match(["put", "patch"], "update/{id}", [AdminRoleController::class, "update"])->name('update');
        });
        Route::group(["prefix" => "user/", "as" => "user."], function () {
            Route::get("", [AdminUserController::class, 'index'])->name('index');
            Route::get("create", [AdminUserController::class, 'create'])->name('create');
            Route::post("store", [AdminUserController::class, 'store'])->name('store');
            Route::get("edit/{id}", [AdminUserController::class, 'edit'])->name('edit');
            Route::match(['put', "patch"], "update/{id}", [AdminUserController::class, 'update'])->name('update');
            Route::post("update-status", [AdminUserController::class, "updateStatus"])->name("updateStatus");

            Route::get("profile/", [AdminUserController::class, "profile"])->name("profile");
            Route::post("change-admin-password", [AdminUserController::class, "adminNewPassword"])->name("adminNewPassword");
            Route::post("change-admin-email", [AdminUserController::class, "changeAdminEmail"])->name("changeAdminEmail");
            Route::post("change-admin-profile", [AdminUserController::class, "changeAdminAvatar"])->name("changeAdminAvatar");

        });
        Route::group(['prefix' => 'company-information/', 'as' => 'general.'], function () {
            Route::get('', [AdminCompanyDataController::class, 'index'])->name('index');
            Route::post('store', [AdminCompanyDataController::class, 'store'])->name('store');
            Route::post('update/{id}', [AdminCompanyDataController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [AdminCompanyDataController::class, 'destroy'])->name('destroy');
        });
        Route::group(["prefix" => "productcategory/", "as" => "productcategory."], function () {
            Route::get("", [AdminProductCategoryController::class, "index"])->name("index");
            Route::get("create", [AdminProductCategoryController::class, "create"])->name("create");
            Route::post("store", [AdminProductCategoryController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductCategoryController::class, "edit"])->name("edit");
            Route::put("update/{id}", [AdminProductCategoryController::class, "update"])->name("update");
            Route::post('productcategories/sortedDatatable', [AdminProductCategoryController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductCategoryController::class, "updateStatus"])->name("updateStatus");

        });

        Route::group(["prefix" => "product-type/", "as" => "product-type."], function () {
            Route::get("", [AdminProductTypeController::class, "index"])->name("index");
            Route::get("create", [AdminProductTypeController::class, "create"])->name("create");
            Route::post("store", [AdminProductTypeController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductTypeController::class, "edit"])->name("edit");
            Route::put("update/{id}", [AdminProductTypeController::class, "update"])->name("update");
            Route::post('product-types/sortedDatatable', [AdminProductTypeController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductTypeController::class, "updateStatus"])->name("updateStatus");

        });
        Route::group(["prefix" => "social/", "as" => "social."], function () {
            Route::get("", [AdminSocialController::class, "index"])->name("index");
            Route::get("create/", [AdminSocialController::class, "create"])->name("create");
            Route::post("store/", [AdminSocialController::class, "store"])->name("store");
            Route::get("edit/", [AdminSocialController::class, "edit"])->name("edit");
            Route::put("update/", [AdminSocialController::class, "update"])->name("update");
        });
        Route::group(["prefix" => "slider/", "as" => "slider."], function () {
            Route::get("", [AdminSliderController::class, "index"])->name("index");
            Route::get("create", [AdminSliderController::class, "create"])->name("create");
            Route::post("store", [AdminSliderController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminSliderController::class, "edit"])->name("edit");
            Route::match(["put", "patch"], "update/{id}", [AdminSliderController::class, "update"])->name("update");
            Route::post("update-status", [AdminSliderController::class, "updateStatus"])->name("updateStatus");
        });
        Route::group(["prefix" => "unit/", "as" => "unit."], function () {
            Route::get("", [AdminUnitController::class, "index"])->name("index");
            Route::get("create", [AdminUnitController::class, "create"])->name("create");
            Route::post("store", [AdminUnitController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminUnitController::class, "edit"])->name("edit");
            Route::match(["put", "patch"], "update/{id}", [AdminUnitController::class, "update"])->name("update");
            Route::post("update-status", [AdminUnitController::class, "updateStatus"])->name("updateStatus");
        });
        Route::group(["prefix" => "product/", "as" => "product."], function () {
            Route::get("", [AdminProductController::class, "index"])->name("index");
            Route::get("create", [AdminProductController::class, "create"])->name("create");
            Route::post("store", [AdminProductController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductController::class, "edit"])->name("edit");
            Route::get("show/{id}", [AdminProductController::class, "show"])->name("show");
            Route::put("update/{id}", [AdminProductController::class, "update"])->name("update");
            Route::post('products/sortedDatatable', [AdminProductController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductController::class, "updateStatus"])->name("updateStatus");
            Route::delete("delete/{id}", [AdminProductController::class, "destroy"])->name("delete");
            Route::get('get-product-type', [AdminProductController::class, 'childCatBasedOnParent'])->name('get-product-type');

        });
        Route::post('getproducttype', [AdminProductController::class, 'fetchProductType'])->name("getproducttype");

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'slug', 'status', 'order'];

    public function product_types()
    {
        return $this->belongsToMany("App\Models\ProductType", "category_types");
    }
    public function products()
    {
        return $this->hasMany('App\Models\Product', 'product_category_id', 'id');
    }

    public function product_ratings()
    {
        return $this->hasMany('App\Models\ProjectRating', 'product_category_id', 'id');
    }
}

app/Http/Controllers/Admin/ProductCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ProductCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class ProductCategoryController extends Controller
{
    private $page = 'admin.productcategory.';
    private $redirectTo = 'admin.productcategory.index';

    public function index()
    {
        $product_categories = ProductCategory::orderBy('order', 'ASC')->get();
        return view($this->page . 'index', compact('product_categories'))->with('id');
    }
    public function create()
    {
        return view($this->page . 'create');
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            "title" => ["required", "unique:product_categories,title"],
        ]);
        if ($validator->fails()) {
            return response()->json(["errors" => $validator->errors()]);
        }

        if ($validator->passes()) {
            try {
                DB::beginTransaction();
                $input = $request->except("_token");
                $input['slug'] = getSlug($request->title);
                ProductCategory::create($input);
                DB::commit();
                return response()->json(["msg" => "Product category created successfully", "redirectRoute" => route($this->redirectTo)]);
            } catch (\Exception $e) {
                DB::rollBack();
                return response()->json(["db_error" => $e->getMessage()]);
            }
        }

    }
    public function edit($id)
    {
        $product_category = ProductCategory::findOrFail($id);
        return view($this->page . "edit", compact("product_category"));
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => ['required', "unique:product_categories,title," . $id],
        ]);

        if ($validator->fails()) {
            return response()->json(["errors" => $validator->errors()]);
        }
        if ($validator->passes()) {
            try {
                DB::beginTransaction();
                $product_category = ProductCategory::findOrFail($id);
                $input = $request->except("_token");
                $input["slug"] = getSlug($request->title);

                $product_category->update($input);
                DB::commit();
                return response()->json(["msg" => "Product Category updated successfully", "redirectRoute" => route($this->redirectTo)]);
            } catch (\Exception $e) {
                DB::rollBack();
                return response()->json(["db_error" => $e->getMessage()]);
            }
        }
    }

    public function updateOrder(Request $request)
    {
        $product_categories = ProductCategory::all();
        foreach ($product_categories as $product_category) {
            $product_category->timestamps = false;
            $id = $product_category->id;

            foreach ($request->order as $order) {
                if ($order['id'] == $id) {
                    $product_category->update(['order' => $order['position']]);
                }
            }

        }
        return response('Updated successfully.', 200);
    }
    public function updateStatus(Request $request)
    {
        $product_category = ProductCategory::where("id", $request->product_category_id)->first();
        if ($product_category->status == 0) {
            $product_category->update(["status" => 1]);
            $msg = "Product Category is active";
        } else {
            $product_category->update(["status" => 0]);
            $msg = "Product Category is inactive";
        }
        $status = $product_category->status;
        return response()->json(["msg" => $msg, "status" => $status]);

    }
}

resources/views/admin/productcategory/create.blade.php
@extends('layouts.admin.app')
@section('title', 'Product Category')
@section('product-cateogry', 'active')
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                <a>
                                    <span class="content-header">Create Product Category</span>
                                </a>
                                <a href="{{ route('admin.productcategory.index') }}" class="btn btn-primary float-right"><i
                                        class="fa fa-arrow-left iCheck"></i>&nbsp;Back to List</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('admin.productcategory.store') }}" method="POST" enctype="multipart/form-data"
                                id="form">
                                @csrf
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                    <p class="db_error"></p>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="col-md-6">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <label for="title">Title&nbsp;<span class="req">*</span></label>
                                                </div>
                                                <div class="col-md-8">
                                                    <input type="text" name="title" value="{{ old('title') }}"
                                                        class="form-control" placeholder="Enter cateogry title">
                                                    <span class="require title text-danger"></span>
                                                    @error('title')
                                                        <span class="text-danger">{{ $message }}</span>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <label for="status">Status</label>
                                                </div>
                                                <div class="col-md-8">
                                                    <select name="status" class="form-control select2 @error('status') is-invalid @enderror" style="width: 100%">
                                                        <option value="1" {{ old('status') == '1' ? 'selected' : '' }}>
                                                            Active</option>
                                                        <option value="0" {{ old('status') == '0' ? 'selected' : '' }}>
                                                            Inactive</option>
                                                    </select>
                                                    <span class="require status text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                       
                                        <div class="form-group text-center">
                                            <button type="button" class="btn btn-primary"
                                                onclick="submitForm(event);">Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script>
        $(document).ready(function() {
            $(".alert-warning").css('display', 'none');
        });

        function submitForm(e) {
            e.preventDefault();
            $('.require').css('display', 'none');
            let url = $("#form").attr("action");
            $.ajax({
                url: url,
                type: 'post',
                data: new FormData($("#form")[0]),
                processData: false,
                contentType: false,
                cache: false,
                success: function(data) {
                    if (data.db_error) {
                        $(".alert-warning").css('display', 'block');
                        $(".db_error").html(data.db_error);
                    } else if (data.errors) {
                        var error_html = "";
                        $.each(data.errors, function(key, value) {
                            error_html = '<div>' + value + '</div>';
                            $('.' + key).css('display', 'block').html(error_html);
                        });
                    } else if(!data.errors && !data.db_error) {
                        location.href = data.redirectRoute;
                        toastr.success(data.msg);
                    }

                }
            });
        }
    </script>
@endsection

resources/views/admin/productcategory/index.blade.php
@extends('layouts.admin.app')
@section('title', 'Product Category')
@section('product-category', 'active')
@section('content')
   
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <div class="card-header">
                            <div class="card-title">
                                <a>
                                    <span class="content-header">All Product Category</span>
                                </a>
                                <a href="{{ route('admin.productcategory.create') }}" class="btn btn-primary float-right">
                                    <i class="fas fa-plus"></i> Add Product Category
                                </a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">

                            <table id="ProductCategory" class="table table-responsive-xl">
                                <thead>
                                    <tr>
                                        <th>S.N</th>
                                        <th>Title</th>
                                        <th>Status</th>
                                        <th class="hidden">Action</th>
                                    </tr>
                                </thead>
                                <tbody id="sortedtable">
                                    @foreach ($product_categories as $key => $category)
                                        <tr  data-id="{{ $category->id }}" class="sortRow">
                                            <td style='cursor: pointer;'>{{ ++$id }}</td>
                                            <td style='cursor: pointer;'>{{ $category->title }}</td>
                                            <td>
                                                <?php echo $category->status ? '<span class="cur_sor badge badge-success" onclick="updateStatus(' . $category->id . ',$(this))">Active</span>' : '<span class="badge badge-warning cur_sor" onclick="updateStatus(' . $category->id . ',$(this))">Inactive</span>'; ?>
                                            </td>
                                            <td>
                                                <div class="d-inline-flex">
                                                    <a href="{{ route('admin.productcategory.edit', $category->id) }}"
                                                        class="btn btn-sm btn-primary" title="Edit Client Category">
                                                        <i class="fa fa-edit iCheck"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')

    <script>
        $(document).ready(function() {
            $("#ProductCategory").DataTable({
                "responsive": false,
                "lengthChange": true,
                "autoWidth": false,
                "dom": 'lBfrtip',
                "buttons": [{
                        extend: 'collection',
                        text: "<i class='fa fa-ellipsis-v'></i>",
                        buttons: [{
                                extend: 'copy',
                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'csv',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'excel',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'pdf',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'print',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                },

                            },
                        ],

                    },
                    {
                        extend: 'colvis',
                        columns: ':not(.hidden)'
                    }
                ],
                "language": {
                    "infoEmpty": "No entries to show",
                    "emptyTable": "No data available",
                    "zeroRecords": "No records to display",
                }
            });
            dataTablePosition();
        });

         $("#sortedtable").sortable({
            items: "tr",
            cursor: 'move',
            opacity: 0.6,
            update: function() {
                console.log('updated');
                sendOrderToServer();
            }
        });

        function sendOrderToServer() {
            var id = $('tr.sortRow').attr('data-id');
            console.log(id);
            var order = [];
            $('tr.sortRow').each(function(index, element) {
                order.push({
                    id: $(this).attr('data-id'),
                    position: index + 1
                });
            });
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "{{ route('admin.productcategory.updateOrder') }}",
                data: {
                    order: order,
                    _token: '{{ csrf_token() }}'
                },
                success: function(response) {
                    console.log(response);
                    if (response.status == "Success") {
                        console.log(response);
                    } else {
                        console.log(response);
                    }
                }
            });
        }

         function updateStatus(id, el) {
            if (id) {
                $.ajax({
                    url: "{{ route('admin.productcategory.updateStatus') }}",
                    type: 'POST',
                    data: {
                        'product_category_id': id
                    },
                    success: function(data) {
                        if (data.status == 0) {
                            el.text('Inactive');
                            el.removeClass('badge-success').addClass('badge-warning');
                        } else if (data.status == 1) {
                            el.text('Active');
                            el.removeClass('badge-warning').addClass('badge-success');
                        }
                        toastr.success(data.msg);
                    }
                });
            }
        }
    </script>
@endsection