routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController as AdminAboutController;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CartController as AdminCartController;
use App\Http\Controllers\Admin\CityController as AdminCityController;
use App\Http\Controllers\Admin\CompanyDataController as AdminCompanyDataController;
use App\Http\Controllers\Admin\ContactController as AdminContactController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\PermissionController as AdminPermissionController;
use App\Http\Controllers\Admin\PrivacyPolicyController as AdminPrivacyPolicyController;
use App\Http\Controllers\Admin\ProductCategoryController as AdminProductCategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ProductImageController as AdminProductImageController;
use App\Http\Controllers\Admin\ProductRatingController as AdminProductRatingController;
use App\Http\Controllers\Admin\ProductTypeController as AdminProductTypeController;
use App\Http\Controllers\Admin\ProvinceController as AdminProvinceController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\ServiceController as AdminServiceController;
use App\Http\Controllers\Admin\SliderController as AdminSliderController;
use App\Http\Controllers\Admin\SocialController as AdminSocialController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Frontend\FrontendController as FrontendController;
use App\Http\Controllers\Frontend\OrderController as OrderController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes(['register' => true]);

Route::group(["middleware" => ["auth", 'checkPermission']], function () {
    Route::group(["prefix" => "admin/", "as" => "admin."], function () {
        Route::get("dashboard", [AdminDashboardController::class, "dashboard"])->name("dashboard");

        Route::group(["prefix" => "permission/", "as" => "permission."], function () {
            Route::get("", [AdminPermissionController::class, "index"])->name("index");
            Route::get('create', [AdminPermissionController::class, "create"])->name('create');
            Route::post("store", [AdminPermissionController::class, "store"])->name("store");
        });
        Route::group(["prefix" => "role/", "as" => "role."], function () {
            Route::get("", [AdminRoleController::class, 'index'])->name("index");
            Route::get("create", [AdminRoleController::class, 'create'])->name("create");
            Route::post("store", [AdminRoleController::class, 'store'])->name('store');
            Route::get("edit/{id}", [AdminRoleController::class, 'edit'])->name('edit');
            Route::match(["put", "patch"], "update/{id}", [AdminRoleController::class, "update"])->name('update');
        });
        Route::group(["prefix" => "user/", "as" => "user."], function () {
            Route::get("", [AdminUserController::class, 'index'])->name('index');
            Route::get("create", [AdminUserController::class, 'create'])->name('create');
            Route::post("store", [AdminUserController::class, 'store'])->name('store');
            Route::get("edit/{id}", [AdminUserController::class, 'edit'])->name('edit');
            Route::match(['put', "patch"], "update/{id}", [AdminUserController::class, 'update'])->name('update');
            Route::post("update-status", [AdminUserController::class, "updateStatus"])->name("updateStatus");

            Route::get("profile/", [AdminUserController::class, "profile"])->name("profile");
            Route::post("change-admin-password", [AdminUserController::class, "adminNewPassword"])->name("adminNewPassword");
            Route::post("change-admin-email", [AdminUserController::class, "changeAdminEmail"])->name("changeAdminEmail");
            Route::post("change-admin-profile", [AdminUserController::class, "changeAdminAvatar"])->name("changeAdminAvatar");

        });
        Route::group(['prefix' => 'company-information/', 'as' => 'general.'], function () {
            Route::get('', [AdminCompanyDataController::class, 'index'])->name('index');
            Route::post('store', [AdminCompanyDataController::class, 'store'])->name('store');
            Route::post('update/{id}', [AdminCompanyDataController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [AdminCompanyDataController::class, 'destroy'])->name('destroy');
        });
        Route::group(["prefix" => "productcategory/", "as" => "productcategory."], function () {
            Route::get("", [AdminProductCategoryController::class, "index"])->name("index");
            Route::get("create", [AdminProductCategoryController::class, "create"])->name("create");
            Route::post("store", [AdminProductCategoryController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductCategoryController::class, "edit"])->name("edit");
            Route::put("update/{id}", [AdminProductCategoryController::class, "update"])->name("update");
            Route::post('productcategories/sortedDatatable', [AdminProductCategoryController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductCategoryController::class, "updateStatus"])->name("updateStatus");

        });

        Route::group(["prefix" => "product-type/", "as" => "product-type."], function () {
            Route::get("", [AdminProductTypeController::class, "index"])->name("index");
            Route::get("create", [AdminProductTypeController::class, "create"])->name("create");
            Route::post("store", [AdminProductTypeController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductTypeController::class, "edit"])->name("edit");
            Route::put("update/{id}", [AdminProductTypeController::class, "update"])->name("update");
            Route::post('product-types/sortedDatatable', [AdminProductTypeController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductTypeController::class, "updateStatus"])->name("updateStatus");

        });
        Route::group(["prefix" => "social/", "as" => "social."], function () {
            Route::get("", [AdminSocialController::class, "index"])->name("index");
            Route::get("create/", [AdminSocialController::class, "create"])->name("create");
            Route::post("store/", [AdminSocialController::class, "store"])->name("store");
            Route::get("edit/", [AdminSocialController::class, "edit"])->name("edit");
            Route::put("update/", [AdminSocialController::class, "update"])->name("update");
        });
        Route::group(["prefix" => "slider/", "as" => "slider."], function () {
            Route::get("", [AdminSliderController::class, "index"])->name("index");
            Route::get("create", [AdminSliderController::class, "create"])->name("create");
            Route::post("store", [AdminSliderController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminSliderController::class, "edit"])->name("edit");
            Route::match(["put", "patch"], "update/{id}", [AdminSliderController::class, "update"])->name("update");
            Route::post("update-status", [AdminSliderController::class, "updateStatus"])->name("updateStatus");
        });
        Route::group(["prefix" => "unit/", "as" => "unit."], function () {
            Route::get("", [AdminUnitController::class, "index"])->name("index");
            Route::get("create", [AdminUnitController::class, "create"])->name("create");
            Route::post("store", [AdminUnitController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminUnitController::class, "edit"])->name("edit");
            Route::match(["put", "patch"], "update/{id}", [AdminUnitController::class, "update"])->name("update");
            Route::post("update-status", [AdminUnitController::class, "updateStatus"])->name("updateStatus");
        });
        Route::group(["prefix" => "product/", "as" => "product."], function () {
            Route::get("", [AdminProductController::class, "index"])->name("index");
            Route::get("create", [AdminProductController::class, "create"])->name("create");
            Route::post("store", [AdminProductController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductController::class, "edit"])->name("edit");
            Route::get("show/{id}", [AdminProductController::class, "show"])->name("show");
            Route::put("update/{id}", [AdminProductController::class, "update"])->name("update");
            Route::post('products/sortedDatatable', [AdminProductController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductController::class, "updateStatus"])->name("updateStatus");
            Route::delete("delete/{id}", [AdminProductController::class, "destroy"])->name("delete");
            Route::get('get-product-type', [AdminProductController::class, 'childCatBasedOnParent'])->name('get-product-type');

        });
        Route::post('getproducttype', [AdminProductController::class, 'fetchProductType'])->name("getproducttype");

resources/views/layouts/admin/sidebar/allnav.blade.php
<li class="nav-item">
    <a href="{{ route('admin.user.index') }}" class="nav-link @yield('user')">
        <i class="nav-icon fas fa-user-plus iCheck"></i>
        <p>Users</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('admin.permission.index') }}" class="nav-link @yield(" permission")">
        <i class="nav-icon fa fa-circle iCheck"></i>
        <p>Permissions</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('admin.role.index') }}" class="nav-link @yield(" role")">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>Roles</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('admin.unit.index') }}" class="nav-link @yield(" unit")">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>Product Unit</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('admin.brand.index') }}" class="nav-link @yield(" brand")">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>Our Brands</p>
    </a>
</li>
<li class="nav-item {{ $province || $city ? $menu : '' }}">
    <a href="#" class="nav-link {{ $province || $city ? $active : '' }}">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>
            Address
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="{{ route('admin.province.index') }}" class="nav-link @yield('province')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Province</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.city.index') }}" class="nav-link @yield('city')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>City</p>
            </a>
        </li>

    </ul>
</li>

<li class="nav-item {{ $order || $vorder ? $menu : '' }}">
    <a href="#" class="nav-link {{ $order || $vorder ? $active : '' }}">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>
            Manage Order
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="{{ route('admin.order.index') }}" class="nav-link @yield('order')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>All Orders</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link @yield('verified-order')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Verified Orders</p>
            </a>
        </li>

    </ul>
</li>
<li class="nav-item {{ $productcategory || $product || $productType || $productRating ? $menu : '' }}">
    <a href="#" class="nav-link {{ $productcategory || $product || $productType || $productRating ? $active : '' }}">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>
            Product
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="{{ route('admin.productcategory.index') }}" class="nav-link @yield('product-category')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Product Category</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.product-type.index') }}" class="nav-link @yield('product-type')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Product Type</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.product.index') }}" class="nav-link @yield('product')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Product</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.productrating.index') }}" class="nav-link @yield('product-rating')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Product Rating</p>
            </a>
        </li>
    </ul>
</li>
<li class="nav-item">
    <a href="{{ route('admin.contact.index') }}" class="nav-link @yield(" contact")">
        <i class="nav-icon fa fa-hand-point-right iCheck"></i>
        <p>User's Query</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('admin.service.index') }}" class="nav-link @yield(" service")">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>Services</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('admin.cart.index') }}" class="nav-link @yield(" cart")">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>Cart Items</p>
    </a>
</li>
<li class="nav-item {{ $about || $general || $socialNav || $sliderNav ? $menu : '' }}">
    <a href="#" class="nav-link {{ $about || $general || $socialNav || $sliderNav ? $active : '' }}">
        <i class="nav-icon fa fa-th-list iCheck"></i>
        <p>
            General Settings
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="{{ route('admin.privacypolicy.index') }}" class="nav-link @yield(" privacy-policy")">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>Privacy Policy</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.about.index') }}" class="nav-link @yield('about')">
                <i class="nav-icon far fa-circle iCheck"></i>
                <p>About</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.general.index') }}" class="nav-link @yield('general-setting')">
                <i class="nav-icon fa fa-building iCheck"></i>
                <p>Company Information</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.social.index') }}" class="nav-link @yield('social')">
                <i class="nav-icon fa fa-share-alt iCheck"></i>
                <p>Socials</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.slider.index') }}" class="nav-link @yield('slider')">
                <i class="nav-icon fa fa-image iCheck"></i>
                <p>slider</p>
            </a>
        </li>
    </ul>
</li>