routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController as AdminAboutController;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CartController as AdminCartController;
use App\Http\Controllers\Admin\CityController as AdminCityController;
use App\Http\Controllers\Admin\CompanyDataController as AdminCompanyDataController;
use App\Http\Controllers\Admin\ContactController as AdminContactController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\PermissionController as AdminPermissionController;
use App\Http\Controllers\Admin\PrivacyPolicyController as AdminPrivacyPolicyController;
use App\Http\Controllers\Admin\ProductCategoryController as AdminProductCategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ProductImageController as AdminProductImageController;
use App\Http\Controllers\Admin\ProductRatingController as AdminProductRatingController;
use App\Http\Controllers\Admin\ProductTypeController as AdminProductTypeController;
use App\Http\Controllers\Admin\ProvinceController as AdminProvinceController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\ServiceController as AdminServiceController;
use App\Http\Controllers\Admin\SliderController as AdminSliderController;
use App\Http\Controllers\Admin\SocialController as AdminSocialController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Frontend\FrontendController as FrontendController;
use App\Http\Controllers\Frontend\OrderController as OrderController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes(['register' => true]);

Route::group(["middleware" => ["auth", 'checkPermission']], function () {
    Route::group(["prefix" => "admin/", "as" => "admin."], function () {
        Route::get("dashboard", [AdminDashboardController::class, "dashboard"])->name("dashboard");

        Route::group(["prefix" => "permission/", "as" => "permission."], function () {
            Route::get("", [AdminPermissionController::class, "index"])->name("index");
            Route::get('create', [AdminPermissionController::class, "create"])->name('create');
            Route::post("store", [AdminPermissionController::class, "store"])->name("store");
        });
        Route::group(["prefix" => "role/", "as" => "role."], function () {
            Route::get("", [AdminRoleController::class, 'index'])->name("index");
            Route::get("create", [AdminRoleController::class, 'create'])->name("create");
            Route::post("store", [AdminRoleController::class, 'store'])->name('store');
            Route::get("edit/{id}", [AdminRoleController::class, 'edit'])->name('edit');
            Route::match(["put", "patch"], "update/{id}", [AdminRoleController::class, "update"])->name('update');
        });
        Route::group(["prefix" => "user/", "as" => "user."], function () {
            Route::get("", [AdminUserController::class, 'index'])->name('index');
            Route::get("create", [AdminUserController::class, 'create'])->name('create');
            Route::post("store", [AdminUserController::class, 'store'])->name('store');
            Route::get("edit/{id}", [AdminUserController::class, 'edit'])->name('edit');
            Route::match(['put', "patch"], "update/{id}", [AdminUserController::class, 'update'])->name('update');
            Route::post("update-status", [AdminUserController::class, "updateStatus"])->name("updateStatus");

            Route::get("profile/", [AdminUserController::class, "profile"])->name("profile");
            Route::post("change-admin-password", [AdminUserController::class, "adminNewPassword"])->name("adminNewPassword");
            Route::post("change-admin-email", [AdminUserController::class, "changeAdminEmail"])->name("changeAdminEmail");
            Route::post("change-admin-profile", [AdminUserController::class, "changeAdminAvatar"])->name("changeAdminAvatar");

        });
        Route::group(['prefix' => 'company-information/', 'as' => 'general.'], function () {
            Route::get('', [AdminCompanyDataController::class, 'index'])->name('index');
            Route::post('store', [AdminCompanyDataController::class, 'store'])->name('store');
            Route::post('update/{id}', [AdminCompanyDataController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [AdminCompanyDataController::class, 'destroy'])->name('destroy');
        });
        Route::group(["prefix" => "productcategory/", "as" => "productcategory."], function () {
            Route::get("", [AdminProductCategoryController::class, "index"])->name("index");
            Route::get("create", [AdminProductCategoryController::class, "create"])->name("create");
            Route::post("store", [AdminProductCategoryController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductCategoryController::class, "edit"])->name("edit");
            Route::put("update/{id}", [AdminProductCategoryController::class, "update"])->name("update");
            Route::post('productcategories/sortedDatatable', [AdminProductCategoryController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductCategoryController::class, "updateStatus"])->name("updateStatus");

        });

        Route::group(["prefix" => "product-type/", "as" => "product-type."], function () {
            Route::get("", [AdminProductTypeController::class, "index"])->name("index");
            Route::get("create", [AdminProductTypeController::class, "create"])->name("create");
            Route::post("store", [AdminProductTypeController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductTypeController::class, "edit"])->name("edit");
            Route::put("update/{id}", [AdminProductTypeController::class, "update"])->name("update");
            Route::post('product-types/sortedDatatable', [AdminProductTypeController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductTypeController::class, "updateStatus"])->name("updateStatus");

        });
        Route::group(["prefix" => "social/", "as" => "social."], function () {
            Route::get("", [AdminSocialController::class, "index"])->name("index");
            Route::get("create/", [AdminSocialController::class, "create"])->name("create");
            Route::post("store/", [AdminSocialController::class, "store"])->name("store");
            Route::get("edit/", [AdminSocialController::class, "edit"])->name("edit");
            Route::put("update/", [AdminSocialController::class, "update"])->name("update");
        });
        Route::group(["prefix" => "slider/", "as" => "slider."], function () {
            Route::get("", [AdminSliderController::class, "index"])->name("index");
            Route::get("create", [AdminSliderController::class, "create"])->name("create");
            Route::post("store", [AdminSliderController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminSliderController::class, "edit"])->name("edit");
            Route::match(["put", "patch"], "update/{id}", [AdminSliderController::class, "update"])->name("update");
            Route::post("update-status", [AdminSliderController::class, "updateStatus"])->name("updateStatus");
        });
        Route::group(["prefix" => "unit/", "as" => "unit."], function () {
            Route::get("", [AdminUnitController::class, "index"])->name("index");
            Route::get("create", [AdminUnitController::class, "create"])->name("create");
            Route::post("store", [AdminUnitController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminUnitController::class, "edit"])->name("edit");
            Route::match(["put", "patch"], "update/{id}", [AdminUnitController::class, "update"])->name("update");
            Route::post("update-status", [AdminUnitController::class, "updateStatus"])->name("updateStatus");
        });
        Route::group(["prefix" => "product/", "as" => "product."], function () {
            Route::get("", [AdminProductController::class, "index"])->name("index");
            Route::get("create", [AdminProductController::class, "create"])->name("create");
            Route::post("store", [AdminProductController::class, "store"])->name("store");
            Route::get("edit/{id}", [AdminProductController::class, "edit"])->name("edit");
            Route::get("show/{id}", [AdminProductController::class, "show"])->name("show");
            Route::put("update/{id}", [AdminProductController::class, "update"])->name("update");
            Route::post('products/sortedDatatable', [AdminProductController::class, "updateOrder"])->name('updateOrder');
            Route::post("update-status", [AdminProductController::class, "updateStatus"])->name("updateStatus");
            Route::delete("delete/{id}", [AdminProductController::class, "destroy"])->name("delete");
            Route::get('get-product-type', [AdminProductController::class, 'childCatBasedOnParent'])->name('get-product-type');

        });
        Route::post('getproducttype', [AdminProductController::class, 'fetchProductType'])->name("getproducttype");

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'address',
        'avatar',
        'status',
        'user_type',
        'facebook_id',
        'google_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany("App\Models\Role", 'user_roles');
    }
    // public function carts()
    // {
    //     return $this->belongsTo('App\Models\Cart', 'user_id', 'id');

    // }
    public function avatarImg($img)
    {
        if ($img != null && $img != "default.png") {
            return asset(("images/admin/avatar/" . $img));
        }
        return asset("images/default.png");
    }

}

resources/views/admin/user/index.blade.php
@extends('layouts.admin.app')
@section('title', 'User')
@section('user', 'active')
@section('content')
   
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                <a>
                                    <span class="content-header">All Users</span>
                                </a>
                                <a href="{{ route('admin.user.create') }}" class="btn btn-primary float-right">
                                    <i class="fas fa-plus"></i> Add User
                                </a>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="Admin" class="table table-responsive-xl">
                                <thead>
                                    <tr>
                                        <th>S.N</th>
                                        <th>Avatar</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Address</th>
                                        <th>Role</th>
                                        <th>Status</th>
                                        <th class="hidden" style="width:10%">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $key => $user)
                                   
                                        <tr>
                                            <td>{{ ++$id }}</td>
                                            <td>
                                                <img src="{{ $user->avatarImg($user->avatar) }}" class="imageSize"
                                                    alt="">
                                            </td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->phone ? $user->phone : '' }}</td>
                                            <td>{{ $user->address }}</td>
                                            <td>{{ $user->roles()->exists() ? $user->roles()->first()->name : '' }}</td>
                                            <td>

                                                <?php echo $user->status ? '<span class="cur_sor badge badge-success" onclick="updateStatus(' . $user->id . ',$(this))">Active</span>' : '<span class="badge badge-warning cur_sor" onclick="updateStatus(' . $user->id . ',$(this))">Inactive</span>'; ?>


                                            </td>
                                            <td>
                                                <div class="d-inline-flex">

                                                    <a href="{{ route('admin.user.edit', $user->id) }}"
                                                        class="btn btn-primary btn-sm" title="Edit User">
                                                        <i class="fa fa-edit iCheck"></i>
                                                    </a>

                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script>
        $(document).ready(function() {
            $("#Admin").DataTable({
                "responsive": false,
                "autoWidth": false,
                "dom": 'lBfrtip',
                "buttons": [{
                        extend: 'collection',
                        text: "<i class='fa fa-ellipsis-v'></i>",
                        buttons: [{
                                extend: 'copy',
                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'csv',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'excel',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'pdf',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                }
                            },
                            {
                                extend: 'print',

                                exportOptions: {
                                    columns: 'th:not(:last-child)'
                                },

                            },
                        ],

                    },
                    {
                        extend: 'colvis',
                        columns: ':not(.hidden)'
                    }
                ],

                "language": {
                    "infoEmpty": "No entries to show",
                    "emptyTable": "No data available",
                    "zeroRecords": "No records to display",
                }
            });
            dataTablePosition();
        });

        function updateStatus(id, el) {
            console.log(el);
            if (id) {
                $.ajax({
                    url: "{{ route('admin.user.updateStatus') }}",
                    type: 'POST',
                    data: {
                        'user_id': id
                    },
                    success: function(data) {
                        if (data.status == 0) {
                            el.text('Inactive');
                            el.removeClass('badge-success').addClass('badge-warning');
                        } else if (data.status == 1) {
                            el.text('Active');
                            el.removeClass('badge-warning').addClass('badge-success');
                        }
                        toastr.success(data.msg);
                    }
                });
            }
        }
    </script>
@endsection